### ISSUE TITLE
사용자 프로필 클릭시 UserId 넘겨주기

### ISSUE THREAD

**Issue by 1jeongg** [D-VIDE/D-VIDE_Android#98]
### userId가 필요한 화면
- ReviewScreen
- RecruitingScreen
- Following/Follower Screen

**Comment by 1jeongg** [comment]
이전에 onTagClick, onReviewClick 등등처럼 하니까 인자 넘기는게 하나의 Screen단위로 넘어가서 BottomSheet이 아니게 되더라고요,, 그래서 약간 하드코딩이지만 따로 넣어줬습니다!

**Comment by Kick-snare** [comment]
제가 작업하고 있는 것과 관련있는데 서로 다른 viewModel들에게 Composable 인자로 userId를 넘길 때,
아이디로 api를 불러올 것인가...?를 생각해봐야할 것 같습니다.
지금 생각 중인건
1. viewmodel 로 인자 넘기는 법 찾기 (모르겠음)
2. launchedEfffect로 처음 보여질때 호출하기 (뭔가 문제가 있어보임)
3. BottomSheet 개선하기 (BottomSheet이 상위 컴포넌트여서 문제)
